# Using Cursors, Dictionaries and Pandas

In [39]:
import arcpy

In [96]:
fc = "C:\EsriTraining\PYTS\Data\CountyData.gdb\ParcelPts"

In [72]:
sFields = ['Owner_Name', 'Street_Name', 'Street_Number', 'City', 'State', 'SHAPE@XY']

In [63]:
dct = {}

In [98]:
with arcpy.da.SearchCursor(fc, sFields) as sCursor:
    for row in sCursor:
        #print(row[0])
        dct[row[0]] = { 
                        'Address' : "{} {}, {}".format(row[1],
                                                       row[2],
                                                       row[3]),
                        'State' : row[4],
                        'Street' : row[1],
                        'StreetNumber' : row[2],
                        'Geometry' : row[-1]
                      }

In [50]:
from pprint import pprint

In [ ]:
pprint(dct)

In [65]:
toReq = 'Adele Curameng'

if toReq in dct:
    print("The address is {}. The person lives in {}".format(dct[toReq]['Address'],
                                                             dct[toReq]['State']))

The address is Washington Street 3035, Linden. The person lives in  NC

In [66]:
dct['Adele Curameng']

{'Address': 'Washington Street 3035, Linden', 'State': ' NC', 'Street': 'Washington Street', 'StreetNumber': 3035}

In [56]:
import pandas as pd

In [75]:
df = pd.DataFrame(dct).T
df.head()

                                          Address  ...                                 Geometry
Keneth Syers            Hawkins Road 2015, Linden  ...  (2057955.9402780533, 539525.6937791407)
Laurette Albritton  Scott Place Lane 7772, Linden  ...    (2058478.767644465, 535951.779667139)
Alease Howk                Lukes Run 3030, Linden  ...   (2058799.324746132, 535861.5383778065)
Erika Beaven           Ramsey Street 7864, Linden  ...  (2058911.8806233853, 535486.1861101389)
Lowell Pilkins          Burnett Road 1767, Linden  ...   (2058840.165871799, 534811.1910690665)

[5 rows x 5 columns]

In [78]:
df[['x', 'y']] = pd.DataFrame(df['Geometry'].tolist(), index=df.index)
df

                                                  Address  ...              y
Keneth Syers                    Hawkins Road 2015, Linden  ...  539525.693779
Laurette Albritton          Scott Place Lane 7772, Linden  ...  535951.779667
Alease Howk                        Lukes Run 3030, Linden  ...  535861.538378
Erika Beaven                   Ramsey Street 7864, Linden  ...  535486.186110
Lowell Pilkins                  Burnett Road 1767, Linden  ...  534811.191069
...                                                   ...  ...            ...
Kayleigh Wike                     Lane Drive 5740, Linden  ...  535046.860217
Rufus Diehm                   Deerfoot Drive 2706, Linden  ...  534917.709885
Alba Calley                Washington Street 2879, Linden  ...  534691.590258
Tanna Killilea                   Julian Road 7832, Linden  ...  544690.883908
Hailey Vinsel       Hairs Chapel Church Road 5421, Linden  ...  503442.653084

[3242 rows x 7 columns]

In [101]:
df.groupby('Street').count()

                          Address  State  StreetNumber  Geometry    x    y
Street
Big Bay Road                  157    157           157       157  157  157
Bonnie Brook Court            119    119           119       119  119  119
Burnett Road                  126    126           126       126  126  126
Carlos Road                   145    145           145       145  145  145
Deerfoot Drive                130    130           130       130  130  130
Friendly Road                 127    127           127       127  127  127
Giles Road                    133    133           133       133  133  133
Hairs Chapel Church Road      148    148           148       148  148  148
Hawkins Road                  103    103           103       103  103  103
Herrill Baggett Road          111    111           111       111  111  111
Julian Road                   148    148           148       148  148  148
Lane Drive                    129    129           129       129  129  129
Laura Ray Road                111    111           111       111  111  111
Long Hill Drive               118    118           118       118  118  118
Lukes Run                     109    109           109       109  109  109
Main Street                   160    160           160       160  160  160
Myrtle Street                 107    107           107       107  107  107
Pine Burr Drive               133    133           133       133  133  133
Ramsey Street                 156    156           156       156  156  156
Rock Ridge Drive              123    123           123       123  123  123
Roper Drive                   114    114           114       114  114  114
Sandalwood Road               117    117           117       117  117  117
Scott Place Lane              137    137           137       137  137  137
Washington Street             147    147           147       147  147  147
Woodrow Street                134    134           134       134  134  134